// MCP bearer token storage, routed through KronosCore's `SecretStoring` seam so this is the
// ONLY place MCP touches the Keychain at all, and so a test can inject `FakeSecretStore` and
// assert exactly when a read happens.
//
// This item is generated by Kronos itself, the first time MCP is enabled, and stored under the
// app-owned service (`KeychainSecretStore`) — not the legacy `kronos_mcp_token` item an older
// build wrote. Reading an item this exact build did not create is what caused the Keychain
// password dialog on every launch; an item this build wrote itself needs no dialog on any later
// launch signed with the same certificate. The old `kronos_mcp_token` item is left alone
// (never read, never deleted) — a fresh install has no such item to worry about, and nothing
// else in the app still points at it.
//
// The token lives in a user-only file (`FileSecretStore`), not the Keychain: without an Apple
// team id every new build is a stranger to a Keychain item the previous build wrote, and the
// login-password dialog returned after each update. The token only keeps other local processes
// off the loopback server; see FileSecretStore.swift for why a 0600 file is the honest trade.
import Foundation
import KronosCore

public enum MCPKeychain {
    /// The legacy Keychain service name an older build wrote the token under directly
    /// (before this file routed through `SecretStoring`). Kept as a named constant —
    /// never read or deleted by this type — because `scripts/mcp-live-selftest-cases.swift`
    /// asserts this string by identity, and because a legacy item must never be touched
    /// automatically: only the app-owned name below is used by the running app now.
    public static let service = "kronos_mcp_token"

    /// Logical name of the MCP token inside the app-owned secret store.
    static let name = "mcp_token"

    /// The stored bearer token, or nil if none has been generated yet. Reads through
    /// `store`, so a test can inject `FakeSecretStore` and never touch the real Keychain.
    public static func loadToken(store: any SecretStoring = FileSecretStore()) -> String? {
        store.read(name)
    }

    /// Generates a fresh 32-byte token (base64url, no padding) and stores it, overwriting
    /// any previous value. Called once, the first time MCP is enabled.
    ///
    /// Returns nil when the system RNG fails or the write itself fails. This used to be a
    /// `precondition`, which crashed the whole task app because an optional local automation
    /// server could not get 32 random bytes — Kronos is where the user's work lives, and
    /// losing it to a failure in a feature they may not even use is the wrong trade. A nil
    /// here means "MCP disabled"; every other part of the app runs untouched.
    ///
    /// NEVER falls back to a weaker source of randomness: a guessable bearer token would
    /// leave the loopback server open to any local process, which is worse than having no
    /// server at all.
    @discardableResult
    public static func generateAndStoreToken(store: any SecretStoring = FileSecretStore()) -> String? {
        var bytes = [UInt8](repeating: 0, count: 32)
        let status = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
        guard status == errSecSuccess else { return nil }
        let token = base64URLEncode(bytes)
        guard (try? store.write(token, name: name)) != nil else { return nil }
        return token
    }

    /// The token to serve requests with: the stored one, or a freshly generated one when
    /// this is the first time MCP is enabled.  Nil means MCP cannot be secured and must stay
    /// disabled — the caller reports it, and does not start the server.
    public static func token(store: any SecretStoring = FileSecretStore()) -> String? {
        loadToken(store: store) ?? generateAndStoreToken(store: store)
    }

    /// Non-secret: true once a token has been generated. Never reads the Keychain
    /// (`SecretStoring.hasValue`) — used by "has key" style UI checks.
    public static func hasToken(store: any SecretStoring = FileSecretStore()) -> Bool {
        store.hasValue(name)
    }

    /// False when no token could be obtained, i.e. MCP must stay disabled. The call site
    /// starting the server checks this before `start()`.
    public static func isEnabled(_ token: String) -> Bool { !token.isEmpty }

    private static func base64URLEncode(_ bytes: [UInt8]) -> String {
        Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }
}
